### ISSUE TITLE
Popsuty link do prezentacji

### ISSUE THREAD

**Issue by 0mp** [BSD-PL/bsd-pl.github.io#21]
https://bsd-pl.org/assets/talks/2018-09-13_2_Patryk-Keijo-Jaworski_Why-is-ARM-a-Tier-2-platform?.pdf

**Comment by tuvok7** [comment]
Poprawiłem i dodałem pull request

**Comment by 0mp** [comment]
Naprawione w 0bae00ebe5e5c130065593d5834eb7c66b23302b.
