### ISSUE TITLE
Podlinkuj do #bsd-pl na Freenodzie

### ISSUE THREAD

**Issue by 0mp** [BSD-PL/bsd-pl.github.io#5]
Na przykład:

> https://webchat.freenode.net/?channels=%23bsd-pl

**Comment by mulander** [comment]
Przenieśliśmy się na Slacka, [zaproszenie tutaj](https://join.slack.com/t/bsd-pl/shared_invite/enQtNTIyMjU4NTUxOTUzLTQwZjMyNTY2OTRhMzZiNGFhOGM3YWU1YmMwYzNlZThjZGY5ZjMwZTZlM2U3NmMyYzA3OWE4MDkxNDk2NGU1OTQ).
