### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by pkubaj** [BSD-PL/bsd-pl.github.io#6]
HTTPS w 2018r. jest już na stronach z założenia, niezależnie czy są tam dane wrażliwe, czy nie.

**Comment by kwitaszczyk** [comment]
Skonfigurowaliśmy GitHub Pages, aby użyć HTTPS dla własnej domeny. Czekamy na odpowiedź z GitHub, dlaczego opcja włączenia HTTPS nie jest dla nas dostępna.

**Comment by kwitaszczyk** [comment]
Dostaliśmy informację, że certyfikat Let's Encrypt został pomyślnie wydany. Strona jest dostępna pod https://bsd-pl.org/ i w najbliższym czasie zaktualizujemy wszędzie oficjalny adres do strony. Wymusiliśmy również użycie HTTPS, więc osoby po wejściu na http://bsd-pl.org/ zostaną odpowiednio przekierowane.

**Comment by kwitaszczyk** [comment]
Dzięki za zainteresowanie! :)
